#!/bin/sh -ex

DB_NAME=phplist
DB_USER=phplist
DB_PASS=$(mcookie)
VERSION=3.7.0

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com
DOMAIN=www.example.com

SRC=/usr/local/src
WEBROOT=/var/www/phplist

# unpack
unzip "$SRC/phplist-$VERSION.zip" -d "$SRC"
mv "$SRC/phplist-$VERSION/public_html/lists" "$WEBROOT"
mkdir $WEBROOT/docs
cp "$SRC/phplist-$VERSION/README.md" \
    "$SRC/phplist-$VERSION/UPGRADE" \
    "$SRC/phplist-$VERSION/VERSION" \
    "$SRC/phplist-$VERSION/doc/README.commandline" \
    "$WEBROOT/docs/"
install -d /usr/share/turnkey-phplist
install -m 0644 "$SRC/phplist-$VERSION/VERSION" \
    /usr/share/turnkey-phplist/VERSION
install -m 0644 "$SRC/phplist-$VERSION.sha256" \
    /usr/share/turnkey-phplist/release.sha256
chown -R root:root $WEBROOT
rm -rf "$SRC/phplist-$VERSION"

# create phplist cli
PHPLIST_CLI=/usr/local/bin/phplist
cat >$PHPLIST_CLI<<EOF
#!/bin/bash -e
# Run phplist from the command line.
# Access is restricted to users listed in the config file, default: admin
# For reference see: $WEBROOT/docs/README.commandline

set \${USER:=admin}
export USER
export CONFIG=$WEBROOT/config/config.php
php $WEBROOT/admin/index.php \$*
EOF
chmod +x $PHPLIST_CLI

# create plugins placeholder
PHPLIST_PLUGINS=/var/www/phplist-plugins
mkdir -p $PHPLIST_PLUGINS
cat >$PHPLIST_PLUGINS/README.txt<<EOF
Create your own pages to slot into PHPlist, or do certain things are are more
specific to your situation.

Default plugins found here are symlinks to $WEBROOT/admin/plugins

Note: To enable uploading of files (images etc) by ckeditor create the dir like this:

    mkdir -p $WEBROOT/uploadimages
    chown -R www-data:www-data $WEBROOT/uploadimages
EOF

# grant ownership to webserver (support installing plugins from webUI)
chown -R www-data:www-data $PHPLIST_PLUGINS

# symlink default plugins so they work OOTB
for plugin in $WEBROOT/admin/plugins/*; do
    ln -s $plugin $PHPLIST_PLUGINS/$(basename $plugin)
done

# configure apache
a2dissite 000-default
a2ensite phplist
a2enmod rewrite

# start services
service mysql start
service apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# tweak configuration
CONFIG=$WEBROOT/config/config.php
# extended config contains ALL options, otherwise some sed lines wont run
cp $WEBROOT/config/config_extended.php $CONFIG

sed -i "s|^\$database_name.*|\$database_name = \"$DB_NAME\";|" $CONFIG
sed -i "s|^\$database_user.*|\$database_user = \"$DB_USER\";|" $CONFIG
sed -i "s|^\$database_password.*|\$database_password = \'$DB_PASS\';|" $CONFIG
sed -i "s|^\$database_connection_ssl_ca.*|\$database_connection_ssl_ca = null;|" $CONFIG
sed -i "s|^\$installation_name.*|\$installation_name = \'TurnKey PHPlist\';|" $CONFIG
sed -i "s|^\$table_prefix.*|\$table_prefix = \"\";|" $CONFIG
sed -i "s|^\$usertable_prefix.*|\$usertable_prefix = \"\";|" $CONFIG
sed -i "s|^\$pageroot.*|\$pageroot = \'\';|" $CONFIG
sed -i "s|^\$adminpages.*|\$adminpages = \'/admin\';|" $CONFIG
sed -i "s|NOSTATSCOLLECTION.*|NOSTATSCOLLECTION\', 1);|" $CONFIG
sed -i "s|^define('PHPMAILERHOST'.*|define('PHPMAILERHOST', 'localhost');|" $CONFIG
sed -i "s|^define('PLUGIN_ROOTDIR.*|define('PLUGIN_ROOTDIR', '$PHPLIST_PLUGINS');|" $CONFIG
sed -i "s|^define('EMAILTEXTCREDITS.*|define('EMAILTEXTCREDITS', 1);|" $CONFIG
sed -i "s|^define('PAGETEXTCREDITS.*|define('PAGETEXTCREDITS', 1);|" $CONFIG
sed -i "s|^define('TEST'.*|define ('TEST', 0);|" $CONFIG

# curl based install
URL="http://127.0.0.1/admin/?page=initialise&firstinstall=1"
CURL="curl --fail --silent --show-error -c /tmp/phplist-install-cookie -b /tmp/phplist-install-cookie"
DATA="firstinstall=1&page=initialise&adminname=admin&orgname=TurnKey+Linux&adminemail=mail%40example.com&adminpassword=turnkeylinux"
$CURL -d $DATA $URL
rm -f /tmp/phplist-install-cookie

# set default ckeditor path while the database is still running
$MYSQL_BATCH --execute "INSERT INTO phplist.config (item, value, editable, type) VALUES ('kcfinder_path', 'plugins/CKEditorPlugin/kcfinder','1',NULL)"

# set default password for good measure
/usr/lib/inithooks/bin/phplist.py --email=$ADMIN_MAIL --pass=$ADMIN_PASS --domain=$DOMAIN

# update email text and html signature
OLD_TEXT="powered by phpList, www.phplist.com"
NEW_TEXT="Powered by TurnKey PHPlist, https://www.turnkeylinux.org/phplist"

OLD_HTML="\$html\[\"signature\"\] = \$PoweredByText;"
NEW_HTML="\$html\[\"signature\"\] = \'<div style=\"clear: both; font-family: arial, verdana, sans-serif; font-size: 8px; font-variant: small-caps; font-weight: normal; padding: 2px; padding-left:10px;padding-top:20px;\">Powered by <a href=\"https://www.turnkeylinux.org/phplist\" target=\"_blank\">TurnKey PHPlist</a></div>\';"

sed -i "s|$OLD_TEXT|$NEW_TEXT|" $WEBROOT/admin/sendemaillib.php
sed -i "s|$OLD_HTML|$NEW_HTML|" $WEBROOT/admin/sendemaillib.php

# stop services
service mysql stop
service apache2 stop
